fix: download jq if it's not available

diff --git a/.github/get-node b/.github/get-node
--- a/.github/get-node
+++ b/.github/get-node
@@ -1,19 +1,18 @@
 #!/usr/bin/env bash
 
-# Exit immediately if a command fails and is not controlled.
-set -e
-
 # Save program arguments to later pass on init binary.
 init_args="$@"
 
 # Common urls.
 new_issue_url="https://github.com/guackamolly/zero-monitor/issues/new"
 latest_release_url="https://api.github.com/repos/guackamolly/zero-monitor/releases/latest"
+jq_release_url="https://github.com/jqlang/jq/releases/download/jq-1.7.1"
 
 # Installation directory and program paths.
 install_dir="$HOME/.config/zero-monitor"
 bin_path="$install_dir/node"
 init_bin_path="$install_dir/init"
+jq_bin_path="$install_dir/jq"
 
 if [ ! -d "$install_dir" ]; then
     mkdir -p "$install_dir"
@@ -22,6 +21,10 @@ fi
 fatal() {
     printf "$1\n"
     exit 1
+}
+
+jq() {
+    "$jq_bin_path" "$@"
 }
 
 exec_bin() {
@@ -34,10 +37,13 @@ exec_bin() {
 
 download() {
     url="$1"
-    bin_name="$(echo ${url##*/} | cut -d '_' -f1)"
+    if [ -z "$url" ]; then
+        fatal "Failed to extract url, please raise an issue to alert maintainers about this bug.\n$new_issue_url"
+    fi
+    bin_name="$(echo ${url##*/} | cut -d '_' -f1 | cut -d '-' -f1)"
 
     printf "Downloading $bin_name ...\n"
-    curl -s -L "$url" -o "$install_dir/$bin_name"
+    wget -O "$install_dir/$bin_name" "$url"
     chmod +x "$install_dir/$bin_name"
 }
 
@@ -57,10 +63,14 @@ armv7l) arch="arm" ;;
 *) fatal ""$(uname -m)" isn't supported right now, please raise an issue to get support on this architecture.\n$new_issue_url" ;;
 esac
 
+# Download jq if not available.
+if [ ! -f "$jq_bin_path" ]; then
+    download "${jq_release_url}/jq-${os}-${arch}"
+fi
+
 # Head latest release
-response=$(curl -s "$latest_release_url")
-status="$(echo $response | jq .status)"
-if [[ "$status" == '"404"' ]]; then
+response=$(wget -qO- "$latest_release_url")
+if ! [[ $? == 0 ]]; then
     fatal "Failed to head release, please raise an issue to alert maintainers about this bug.\n$new_issue_url"
 fi
 
